name : A workflow to echo hello world on merge
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: echo hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello world
